app:
  scheduler:
    enable: true
    interval: 90000
    force-check-delay: 90000
  baseUrlGitHub: "https://api.github.com"
  baseUrlStackOverflow: "https://api.stackexchange.com/2.3"
  baseUrlBot: "http://localhost:8090"
  database-access-type: jpa
  type-linear: "linear"
  type-constant: "constant"
  type-exponential: "exponential"
  error-filters:
    - "e400"
    - "e404NotFound"
    - "e404Empty"
    - "e500"
    - "e409"
  rate-limit:
    read:
      count: 1
      tokens: 1
      period: 1
    write:
      count: 1
      tokens: 1
      period: 1
spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver


server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
