app:
  telegram-token: "${TELEGRAM_TOKEN}"
  register: "Please register using /start command"
  registered: "Registered, hello, dear user"
  alreadyRegistered: "You have already been registered"
  notUnderstand: "I can not understand you, use /help command to proceed"
  sendLink: "Now send a link in next message"
  linksHeader: "Here you are: "
  done: "Done"
  pattern: "^(https?://)?([\\w\\Q$-_+!*'(),%\\E]+\\.)+(\\w{2,63})(:\\d{1,4})?([\\w\\Q/$-_+!*'(),%\\E]+\\.?[\\w\\Q$-_+!*'(),%\\E={0-5}?&.])*/?$"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
