app:
  telegram-token: ${TELEGRAM_TOKEN}
  baseUrlScrapper: "http://localhost:8080"
  register: "Please register using /start command"
  registered: "Registered! Hello, dear "
  alreadyRegistered: "You have already been registered"
  notUnderstand: "I can not understand you, use /help command to proceed"
  sendLink: "Now send a link in next message"
  linksHeader: "Here you are: "
  emptyList: "You have no links being tracked. Print /track to add a link"
  done: "Done: "
  notTracked: "This link is not tracked: "
  pattern: "^(https?://){1}([\\w\\Q$-_+!*'(),%\\E]+\\.)+(\\w{2,63})(:\\d{1,4})?([\\w\\Q/$-_+!*'(),%\\E]+\\.?[\\w\\Q$-_+!*'(),%\\E={0-5}?&.])*/?$"

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml


