/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables.records;


import edu.java.scrapper.domain.jooq.tables.Events;

import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EventsRecord extends TableRecordImpl<EventsRecord> implements Record2<String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>EVENTS.EVENT</code>.
     */
    public void setEvent(@NotNull String value) {
        set(0, value);
    }

    /**
     * Getter for <code>EVENTS.EVENT</code>.
     */
    @jakarta.validation.constraints.NotNull
    @Size(max = 1000000000)
    @NotNull
    public String getEvent() {
        return (String) get(0);
    }

    /**
     * Setter for <code>EVENTS.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>EVENTS.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<String, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row2<String, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<String> field1() {
        return Events.EVENTS.EVENT;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return Events.EVENTS.LINK_ID;
    }

    @Override
    @NotNull
    public String component1() {
        return getEvent();
    }

    @Override
    @NotNull
    public Long component2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public String value1() {
        return getEvent();
    }

    @Override
    @NotNull
    public Long value2() {
        return getLinkId();
    }

    @Override
    @NotNull
    public EventsRecord value1(@NotNull String value) {
        setEvent(value);
        return this;
    }

    @Override
    @NotNull
    public EventsRecord value2(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public EventsRecord values(@NotNull String value1, @NotNull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    @ConstructorProperties({ "event", "linkId" })
    public EventsRecord(@NotNull String event, @NotNull Long linkId) {
        super(Events.EVENTS);

        setEvent(event);
        setLinkId(linkId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(edu.java.scrapper.domain.jooq.tables.pojos.Events value) {
        super(Events.EVENTS);

        if (value != null) {
            setEvent(value.getEvent());
            setLinkId(value.getLinkId());
            resetChangedOnNotNull();
        }
    }
}
